### ISSUE TITLE
Bugs with gcd.sh (gcd-rpc 1.0.0)

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/google-cloud-datastore#109]
_From @sebelga on April 18, 2016 17:55_

Hello,

I know that the gcd.sh is a temporary fix until the gcloud emulator support gRPC but here are a few things that I noticed:
- generated IDs are incremental (1, 2, 3, 4, 5...) instead of the _random_ 16 figures number.
- queries don't work if we don't set a "limit"

Nothing big but just letting you know.
Thanks for the great work!

_Copied from original issue: GoogleCloudPlatform/gcloud-node#1242_

**Comment by stephenplusplus** [comment]
Thanks for the kind words :) This is just an issue tracker for gcloud-node, but I'll bring in @pcostell -- is there another place to report bugs/ask questions specific to the gcd tool that we can direct folks?

**Comment by stephenplusplus** [comment]
_From @sebelga on April 18, 2016 18:1_

Yeah sorry, I didn't know where to share that info :) I'll move it wherever @pcostell tells us.

**Comment by stephenplusplus** [comment]
_From @pcostell on April 18, 2016 18:9_

Moving them to [GoogleCloudPlatform/google-cloud-datastore issue tracker](https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues) is probably the best place for now.

**Comment by sebelga** [comment]
Update:
When using ds.allocateIds, the generated IDs are OK. It is only when creating uncompleted keys, then saving those that the "incremental behaviour" mentioned above applies. It is actually incremental through all entities created (any _kind_).
