### ISSUE TITLE
External FR: Return MutationResults even if there is an error

### ISSUE THREAD

**Issue by pcostell** [googleapis/google-cloud-datastore#112]
From: https://groups.google.com/forum/#!topic/gcd-discuss/RVh3aelMrPw

Given that I already have an entity in my dataset [Test:"id2"], when I run this json as a commit

```
{
    "mode": "NON_TRANSACTIONAL",
    "mutations": [
    {
        "insert": {
          "key": {"path": [{"kind": "Test", "name": "id2"}]},
          "properties": { "stringVal": {"stringValue": "This is a test value."}},
        }
    },
    {
        "insert": {
          "key": {"path": [{"kind": "Test"}]},
          "properties": { "stringVal": {"stringValue": "This is a test value."}},
        }
    },
    ]
}
```

I receive this response

```
{
 "error": {
  "code": 400,
  "message": "entity already exists: app: \"projectID\"\npath <\n  Element {\n    type: \"Test\"\n    name: \"id2\"\n  }\n>\n",
  "status": "INVALID_ARGUMENT"
 }
}
```

Which is fine and all, except that because of the one error I no longer get to know what the automatically id assigned to the other successful insert mutation is. And yes, the other insert mutation is still executed.

What I propose is, add a new field to mutation result called "error." This allows for the developer to know which mutation threw the error, and also allows for the other mutation results, possibly containing important information, to be passed back to the developer as well.
With the proposed change, running the aforementioned JSON will result in this response:

```
{
 "mutationResults": [
  {
   "error": {
    "code": 400,
    "message": "entity already exists: app: \"projectID\"\npath <\n  Element {\n    type: \"Test\"\n    name: \"id2\"\n  }\n>\n",
    "status": "INVALID_ARGUMENT"
   }
  },
  {
   "key": {
    "partitionId": {"projectId": "encoded-source-124205"},
    "path": [{"kind": "Test", "id": "5725107787923456"}]
   }
  }
 ],
 "indexUpdates": 3
}
```

The one exception to this change I can think of is for transactional commits. Seeing as they are all or none, there would be no reason for individual mutation results to be returned when an error occurs.
…

**Comment by BAM5** [comment]
Another call I realized that this may apply to is allocateIds, when a call is made with a bunch of keys and someone makes an error and also sends a key with an id, do the incomplete keys still get allocated? I don't know of a way to view allocated ids so I can't  check. But if so, then that one key with an id is causing the dataset to lose all the ids that are allocated.

**Comment by eddavisson** [comment]
The AllocateIds() call is all-or-nothing. If validation fails (e.g. because one of the keys in the request already had an ID), then no IDs will be allocated.

**Comment by BAM5** [comment]
Good to know. It should be documented on the api page.

**Comment by meredithslota** [comment]
https://cloud.google.com/datastore/docs/reference/data/rest/v1/projects/allocateIds and https://cloud.google.com/datastore/docs/reference/data/rest/v1beta3/projects/allocateIds include documentation for `allocateIds`.
