### ISSUE TITLE
gcd grpc emulator misbehaving with ipv4/ipv6 listen address

### ISSUE THREAD

**Issue by pcostell** [googleapis/google-cloud-datastore#113]
From https://code.google.com/p/google-cloud-sdk/issues/detail?id=769

1) Run the (new grpc) gcd emulator inside of any ubuntu w/java-jre docker-container, and attempt to forward dockerhost:10000 to dockercontainer:8080.
2) Attempt to curl dockerhost:10000, notice that GCD is unreachable.
3) Attempt to curl localhost:8080 from inside the docker container, notice that you receive "Ok" (indicating GCD is indeed running):
  docker exec -it <CONTAINER_ID> curl localhost:8080

BEGIN EXAMPLE DOCKERFILE

```
docker build -t test .
docker run --rm -p 8080-8081:8080-8081 test

FROM java:7-jre

RUN apt-get update
RUN apt-get install -y python curl net-tools socat

RUN wget https://storage.googleapis.com/gcd/tools/gcd-grpc-1.0.0.zip
RUN unzip gcd-grpc-1.0.0.zip
```

```
# Does not work
CMD gcd/gcd.sh create test && gcd/gcd.sh start ./test

# Does work (forwarding ipv6->ipv4)
# CMD socat TCP6-LISTEN:8081,fork TCP4:0.0.0.0:8080 & gcd/gcd.sh create test && gcd/gcd.sh start ./test
```

Thanks for the new grpc implementation! The new emulator may be binding addresses in a strange way, as I'm unable to reach it from outside a docker-container.

Inside the container, I noticed that it listens on an ipv4 local address, but an ipv6 foreign address.

```
root@10c36b89632f:/mnt/data# netstat -lpne
...
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode       PID/Program name
tcp6       0      0 127.0.0.1:8080          :::*                    LISTEN      0          3165434     26/java
```

I'm far from an expert here, but enough poking and experimenting indicates that may be the source of the problem. When I run (other) grpc services inside (other) containers, listening with s.Serve(":1234") I notice that both the local and foreign addresses are ipv6, and if I listen on an ipv4 address with s.Serve("127.0.0.1:1234"), the foreign address is the ipv4 catch-all of 0.0.0.0:*.

I also find that I can reach gcd from outside the container if I manually forward traffic inside the container from ipv6 port to the ipv4 port gcd listens on. e.g.:

```
socat TCP6-LISTEN:8081,fork TCP4:0.0.0.0:8080
```

1) Are there any magic flags or env vars to control the bound address?
2) If not, would it possible to either change or provide the ability to modify the address the new gcd-grpc emulator listens to?

Thanks!
# 

Just noticed my description says ubuntu, but the dockerfile i provided is debian-based. Tried with both actually, same issue, but sorry for the confusing description.

**Comment by pcostell** [comment]
Can you try this newly built emulator? I've added the ability to specify an address with the  `--address` flag: `https://storage.googleapis.com/gcd/tools/gcd-grpc-head.zip`

I'm still trying to figure out exactly what gRPC is doing with ipv4 and ipv6 addresses.

**Comment by cameront** [comment]
Yes -- this seems to work when I run gcd.sh with `--address="::"`

```
$ docker exec fc4bb4 /bin/bash -c 'netstat -lpne'
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode       PID/Program name
tcp6       0      0 :::8080                 :::*                    LISTEN      0          3765145     25/java         
```

Thanks!

**Comment by Draiken** [comment]
Where can I find the appropriate releases for this?
I am having the same problem with the 1.0.0 release and would rather not use a head build, but can't seem to find a place listing all versions

**Comment by pcostell** [comment]
This tool is available through the gcloud command line. You can install it with:

`gcloud components install cloud-datastore-emulator`. 

Right now it's not possible to specify an IPv6 address through the `gcloud` command line, but you can call the tool directly:

```
$GCLOUD_PATH/platform/cloud-datastore-emulator/cloud_datastore_emulator start --host="::" test_dir
```

**Comment by Draiken** [comment]
Okay, I was using the downloaded emulator because [the documentation pointed to it](http://googlecloudplatform.github.io/gcloud-ruby/docs/master/Gcloud/Datastore.html#the-datastore-emulator), not to the gcloud tool.
Thanks anyway
