### ISSUE TITLE
Any alternative way to view the data in the local datastore

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/google-cloud-datastore#116]
_From @susanlinsfu on April 30, 2016 23:34_

Since we have to use gcd-rpc as our local emulator and it doesn't support an admin console, is there some other sort of plugin/view/ready code or alternative method to view the data inside of the datastore?

_Copied from original issue: GoogleCloudPlatform/gcloud-node#1275_

**Comment by mik115** [comment]
hi,
any news about that?
I've started using datastore local emulators and it would be great if there's a tool to inspect datastore content.
Thanks
