### ISSUE TITLE
v1/v1beta3 API usage does not appear in Cloud Console

### ISSUE THREAD

**Issue by eddavisson** [googleapis/google-cloud-datastore#133]
It's visible here:
https://console.developers.google.com/appengine?project=<project-id>

but not here:
https://console.developers.google.com/apis/api/datastore.googleapis.com/overview?project=<project-id>

**Comment by timanovsky** [comment]
Not for me

**Comment by eddavisson** [comment]
The first link (if you add your project ID) should show usage for Datastore Entity Writes, Datastore Entity Deletes, Datastore Read Operations, and Datastore Small Operations -- does that show up for you?

It unfortunately does not show the current rate of these usages.

**Comment by richardkazuomiller** [comment]
I'm experiencing this as well. App Engine shows data for v1beta2 requests but nothing for v1beta3. API Manager shows an empty graph for v1/v1beta3

**Comment by richardkazuomiller** [comment]
Is this going to be fixed? Why is Datastore the only API that doesn't have a graph of requests?

**Comment by timanovsky** [comment]
Yeah, that's very frustrating: google shutting down working API, and replaces with new API without "beta" label but whcih simply does not work. We are doing crazy things running API without monitoring in production.

@richardkazuomiller 
Please upvote hee if you have not yet: https://code.google.com/p/google-cloud-platform/issues/detail?id=82&q=product%3DDeveloperConsole&colspec=ID%20Type%20Product%20Status%20Stars%20Summary%20Priority%20Owner%20Log#makechanges

**Comment by meredithslota** [comment]
Closing in favor of linked issue above.
