### ISSUE TITLE
Java demos need a readme

### ISSUE THREAD

**Issue by paul-hammant** [googleapis/google-cloud-datastore#173]
The readme needs to instruct things like:

```
export DATASTORE_PROJECT_ID=<your-googlecloud-app-id>
mvn exec:java -Dexec.mainClass="com.google.datastore.v1.demos.trivial.Adams" -Dexec.args=<your-googlecloud-app-id>
```
It should also suggest that the user goes and looks at `https://console.cloud.google.com/datastore/entities` afterwards.

And that some service account setup is needed up front. i.e. download and mv to:
```
/Users/<username>/.config/gcloud/application_default_credentials.json
```

**Comment by wsh** [comment]
Interesting suggestions! Would you like to submit a pull request to accomplish them?

**Comment by paul-hammant** [comment]
I could do but I'm hardly an expert on the things I pined for here, as I transition from ignorant to noob

**Comment by meredithslota** [comment]
Java code has been moved to https://github.com/googleapis/java-datastore/tree/master/datastore-v1-proto-client and README has been updated there.
