### ISSUE TITLE
Add NDB Python library

### ISSUE THREAD

**Issue by jturmel** [googleapis/google-cloud-datastore#2]
[b/11319745](http://b/11319745)

We already use Google App Engine, it would be nice if the NDB library was available. Do you guys have a timeline on that?

**Comment by anupamme** [comment]
any timeline on when this is coming?

**Comment by lucemia** [comment]
This is what I created and currently using in production. https://github.com/lucemia/gcloud-python-orm

**Comment by anupamme** [comment]
@lucemia not clear to me what changes I need to do so that the result of this code get reflected in my datastore. e.g. I ran testInsert code expecting that it will be insert data into my datastore but it does not (I am a ndb noob here so this assumption may be stupid).

**Comment by lucemia** [comment]
@anupamme 

1. Setup cloud datastore

```python
# gcloud-datstore
from gcloud import datastore
from gcloudorm import model
dataset = datastore.get_dataset(
    [dataset_id],
    [service_account],
    [p12-key]
)

model.Model.dataset = dataset
```

2. replace ndb with gcloudorm.model

```python
from gcloudorm import model as ndb

class Layout(ndb.Model):
    publisher_id = ndb.IntegerProperty(indexed=False)
    slot_id = ndb.IntegerProperty(indexed=False)
```

**Comment by aatreya** [comment]
@lucemia Are you still working on gcloudorm?

Is there going to be official Google Cloud Platform support for an NDB-like interface to datastore? Should folks just use the App Engine Remote API, or is that going to be deprecated eventually?

**Comment by alexpirine** [comment]
Hi there… any way to use cloud datastore with async or should I just use another database? Not being able to run parallel lookups makes a small page fetch in 6 seconds…

**Comment by obeleh** [comment]
You could use this: https://github.com/transceptor-technology/aiogcd

**Comment by meredithslota** [comment]
The NDB repo is here: https://github.com/googleapis/python-ndb (it's been out for awhile but this issue didn't get updated, apologies).
