### ISSUE TITLE
Document how to use GCD development server in combination with local app engine environment

### ISSUE THREAD

**Issue by obeleh** [googleapis/google-cloud-datastore#21]
[b/11970066](http://b/11970066)

Can I somehow point App Engine Launcher to the GCD development server?
Or if that is not possible. Is there any place where I can put the existing data files so that App Engine can use the existing enities?

**Comment by dragonsinth** [comment]
Any advice on getting golang appengine to work with gcd emulator?  I've been hacking around in the appengine SDK but no luck; even after getting calls redirected, the gcd server doesn't seem to recognize the URL and just returns "Not found".  This is using the gRPC version of the emulator.

**Comment by shauvik** [comment]
@dragonsinth I was able to do it with dev_appserver.py by using `--env_var` to set the env variable: `DATASTORE_EMULATOR_HOST=localhost:8081` 

PS: There is no admin UI for the local GCD emulator https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/148
