### ISSUE TITLE
Elaborate on what arguments are expected by add_projection()

### ISSUE THREAD

**Issue by xennygrimmato** [googleapis/google-cloud-datastore#224]
I am referring to the Python client's `helper.py` file. I want to add projections to a query using the add_projection() method. What is the expected type of the projection argument? As per the test file, I can pass a string, but what if I want to add multiple projections? I can't pass a Python list to the method, I get an error saying that the expected type is bytes or unicode.

**Comment by meredithslota** [comment]
Hi there! This is documented here: https://cloud.google.com/appengine/docs/legacy/standard/java/datastore/projectionqueries. If that documentation doesn't address your specific question or you're still stuck, please file a bug on that page (there's a "Feedback" option). Thanks!
