### ISSUE TITLE
Datastore - Failed to load from the backing store - java.lang.ClassNotFoundException: com.google.cloud.datastore.emulator.impl.LocalDatastoreFileStub

### ISSUE THREAD

**Issue by chalcrow** [googleapis/google-cloud-datastore#229]
We raised an issue for this here - https://github.com/googleapis/google-cloud-java/issues/4661

That may not be the best repo to raise the issue against, as @ajaaym is having difficulty finding the class `LocalDatastoreFileStub$FileProfile`, that the error relates to. Can anyone here advise on this issue?

**Comment by crwilcox** [comment]
Hi @chalcrow. I posted a link to the correct issue tracker for issues with the datastore emulator. For future reference you can find a list of issue trackers here: https://cloud.google.com/support/docs/issue-trackers

**Comment by Tomucha** [comment]
@chalcrow Hi! Did you manage to solve this issue somehow? I'm experiencing the same problem:
LocalDatastoreFileStub$FileProfile after importing data from cloud Datastore ...

**Comment by lebloism** [comment]
@chalcrow @Tomucha Hi ! I got the same error. Did one of you manage to solve this issue somehow ? Thanks

**Comment by Tomucha** [comment]
Sorry, I have no idea :-/

**Comment by meredithslota** [comment]
FYI, the Java code has been moved to https://github.com/googleapis/java-datastore/tree/master/datastore-v1-proto-client - if you are still experiencing emulator issues, please use the public issue tracker linked above, or for issues with the java-datastore client, please use this link: https://github.com/googleapis/java-datastore/issues
