### ISSUE TITLE
oauth2client is archived

### ISSUE THREAD

**Issue by elharo** [googleapis/google-cloud-datastore#243]
The Python code depends on

'oauth2client>=2.0.1,<4.0.0',

which library is archived and likely doesn't work anymore: https://github.com/googleapis/oauth2client

We need to move to google-auth and oauthlib or turn this down.

**Comment by parthea** [comment]
@kolea2 I've downgraded the priority of this issue as part of the Yoshi FixIt. Please adjust the priority as needed.

**Comment by meredithslota** [comment]
We will be turning this down as current development is happening elsewhere. I did confirm that the current client does not have this issue: https://github.com/googleapis/python-datastore/blob/main/setup.py
