### ISSUE TITLE
Error when importing from google.cloud import datastore

### ISSUE THREAD

**Issue by SaschaHeyer** [googleapis/google-cloud-datastore#249]
Hi Folks,

when importing `from google.cloud import datastore` we are getting the following error.

```
from google.cloud import datastore
AttributeError: module 'grpc.experimental.aio' has no attribute 'UnaryUnaryCall'
```

Using the following version `google-cloud-datastore==1.10.0`

Is this a known issue?

**Comment by BenWhitehead** [comment]
Hi @SaschaHeyer, The primary repo for the python datastore client is https://github.com/googleapis/python-datastore

The folks monitoring that repo will be more able to help you dig into this issue. Can you please re-open this over there?

**Comment by kolea2** [comment]
Closing due to ask to open issue in python-datastore repo
