### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by elharo** [googleapis/google-cloud-datastore#260]
RROR:   py27: InvocationError for command /home/travis/build/GoogleCloudPlatform/google-cloud-datastore/python/.tox/py27/bin/python -m pip install --exists-action w .tox/.tmp/package/1/googledatastore-7.0.2.zip (exited with code 1)
The command "cd $TEST_DIR && $TEST_CMD" exited with 1

**Comment by parthea** [comment]
@kolea2 I've downgraded the priority of this issue as part of the Yoshi FixIt. Please adjust the priority as needed.

**Comment by parthea** [comment]
I'm going to close this issue as CI is no longer running on [master](https://github.com/googleapis/google-cloud-datastore/commits/master). Please feel free to re-open it if this is still an issue.
