### ISSUE TITLE
TaskQueue + DataStore Transactions Protobuf API

### ISSUE THREAD

**Issue by upio** [googleapis/google-cloud-datastore#63]
You can transactionally put items to the TaskQueue and DataStore in Appengine but not in Compute or Container Engine. It would be great if the Datastore Protobuf API supported TaskQueue puts as part of the transaction.

Something like:

``` java
CommitRequest.Builder crBuilder = CommitRequest.newBuilder()
  .setTransaction(tx)
cr.getMutationBuilder()
  .addInsertAutoId(entity)
  .addTask(task)

datastore.commit(crBuilder.build())
```

**Comment by meredithslota** [comment]
Task Queues are now Cloud Tasks (https://cloud.google.com/tasks/docs/migrating).
