### ISSUE TITLE
DatastoreHelper should allow for null values on get methods 

### ISSUE THREAD

**Issue by skim1420** [googleapis/google-cloud-datastore#67]
Currently if the value is null, the get methods will throw a IllegalArgumentException. It would be nice to just return null in this case.

**Comment by caioiglesias** [comment]
I have just seen this behaviour.

**Comment by meredithslota** [comment]
Feature work is actively continuing in this two repos: https://github.com/googleapis/python-datastore and https://github.com/googleapis/java-datastore (other libraries for other languages exist, too, but only Java and Python were previously developed from this repo; see also: https://cloud.google.com/datastore/docs/reference/libraries). A lot has changed in the intervening years so I'm no longer sure if this is relevant, apologies. If it is, please file a new issue in the appropriate repo. Thanks!
