### ISSUE TITLE
How should non-appengine clients configure indexes?

### ISSUE THREAD

**Issue by tseaver** [googleapis/google-cloud-datastore#74]
The [index configuration docs](https://cloud.google.com/datastore/docs/tools/indexconfig) presume that the client is a GAE application, with an XML file, `dataset-indexes.xml`.  How whould JSON / protobuf API users submit such configuration?

**Comment by tseaver** [comment]
Related:

- https://github.com/GoogleCloudPlatform/gcloud-python/issues/1143
- http://stackoverflow.com/questions/32607351/412-no-matching-index-found-while-executing-a-query-in-cloud-datastore

**Comment by eddavisson** [comment]
The `gcd` tool (https://cloud.google.com/datastore/docs/tools/) is designed to handle this use case, but there are a few limitations.

If you're using the protobuf API, you can run your code against gcd to have it generate index configuration based on the queries you make. The workflow would be:

```
gcd.sh create -d my-dataset my-project
gcd.sh start my-project
# ...execute queries against gcd...
gcd.sh updateindexes my-project
```

`gcd` doesn't yet support JSON, so in that case, you'd need to manually edit the file:

```
gcd.sh create -d my-dataset my-project
# ...manually create/edit my-project/WEB-INF/datastore-indexes.xml
gcd.sh updateindexes my-project
```
