### ISSUE TITLE
Support disabling built-in indexes on a per-project basis

### ISSUE THREAD

**Issue by pcostell** [googleapis/google-cloud-datastore#83]
Rather than specifying the information in each entity.

**Comment by srikkbhat** [comment]
It would be great to have this at kind level rather than project level. Some terminology in index.yaml file which tells datastore that user will define all their indexes for a kind.

**Comment by kordianbruck** [comment]
Is there any update on this Issue? We are facing having multiple indices that are not used and are multiples in size of the actual data for simple Integer & Date fields. (Data 300-400MB and Index being above 8GB)

That one entity has close to 38GB, while in reality a single index + one composite would suffice for our use case.

**Comment by jordanarseno** [comment]
@pcostell any update on this? Is it on the roadmap?

**Comment by CarreauClement** [comment]
Any update on this ? Anyone know how to disable built-in indexes ? I will only filter on 1 field so I don't need all these built-in indexes and I'd like to remove them.

**Comment by meredithslota** [comment]
Feature work is actively continuing in this two repos: https://github.com/googleapis/python-datastore and https://github.com/googleapis/java-datastore (other libraries for other languages exist, too, but only Java and Python were previously developed from this repo; see also: https://cloud.google.com/datastore/docs/reference/libraries). A lot has changed in the intervening years so I'm no longer sure if this is relevant, apologies. If it is, please file a new issue in the appropriate repo. Thanks!

Related to the topic of indexes, new and updated documentation for managing indexes can be found here: https://cloud.google.com/datastore/docs/tools/indexconfig and the REST reference here: https://cloud.google.com/datastore/docs/configure-indexes-rest-api
