### ISSUE TITLE
provide a canonical web-safe representation of a key

### ISSUE THREAD

**Issue by eddavisson** [googleapis/google-cloud-datastore#88]
http://stackoverflow.com/questions/34875502/provide-web-safe-representation-of-key-that-i-can-use-to-look-up-the-entity

**Comment by meredithslota** [comment]
@eddavisson Any updates in the intervening years?

**Comment by eddavisson** [comment]
There's no single canonical URL-safe representation of a key, and we don't currently plan to define one.

Some specific client libraries do provide this functionality:

* In the [Java client](https://github.com/googleapis/java-datastore), the [Key](https://cloud.google.com/java/docs/reference/google-cloud-datastore/latest/com.google.cloud.datastore.Key) class provides [toUrlSafe](https://cloud.google.com/java/docs/reference/google-cloud-datastore/latest/com.google.cloud.datastore.Key#com_google_cloud_datastore_Key_toUrlSafe__) and [fromUrlSafe](https://cloud.google.com/java/docs/reference/google-cloud-datastore/latest/com.google.cloud.datastore.Key#com_google_cloud_datastore_Key_fromUrlSafe_java_lang_String_) methods.

* In [ndb for Python 3](https://github.com/googleapis/python-ndb), the Key class provides both [urlsafe](https://googleapis.dev/python/python-ndb/latest/key.html#google.cloud.ndb.key.Key.urlsafe) and [to_legacy_urlsafe](https://googleapis.dev/python/python-ndb/latest/key.html#google.cloud.ndb.key.Key.to_legacy_urlsafe) methods. The constructor accepts a [serialized](https://googleapis.dev/python/python-ndb/latest/key.html#google.cloud.ndb.key.Key) key as an input parameter.

The URL-safe formats used by the Java and Python libraries are not compatible with each other.
