### ISSUE TITLE
saving to timestamp_microseconds_value but upon query value is in integer_value

### ISSUE THREAD

**Issue by ghost** [googleapis/google-cloud-datastore#89]
Hi,

I use the local gcd tool to emulate the datastore locally. I also use the python googledatastore library to interact with the datastore. I have a situation where I save a property on an entity, saving the property value under timestamp_microseconds_value.

I later run a query getting back the entity, and try inspect the  timestamp_microseconds_value value which comes back as 0. On closer inspection I noticed that the value I saved is under the property value integer_value.

I printed to console the entity before saving to ensure I am saving to timestamp_microseconds_value, so I'm pretty sure I am not saving incorrectly.

I looked a little at the googledatastore helper python library, and found nothing out of the ordinary in how it saves and accesses timestamp_microseconds_value values of properties.

There's nothing particularly interesting in the gcd logs when I save or query. I'm using java 1.7.0, and gcd downloaded from https://cloud.google.com/datastore/docs/downloads
Has anyone had this before or seen such behaviour?

**Comment by eddavisson** [comment]
@hir3npatel, is your query a projection query? There is a quirk in the API resulting from how we implement indexes. It means that in projection query results, values that are normally in the `timestamp_microseconds_value` field are moved to the `integer_value` field.

**Comment by hir3npatel** [comment]
Hi,

Yes my query is a projection query indeed. Thanks for the info. Is this case in production too? (not just the gcd tool for local emulation?) Can I expect the same behaviour in production then?

**Comment by eddavisson** [comment]
Yep, you'll see the same behavior in prod. I'll leave this issue open as it does seem to be a gap in our documentation.

**Comment by hir3npatel** [comment]
Okay thanks. Ah I see it is mentioned here https://cloud.google.com/datastore/docs/concepts/projectionqueries but very subtle in the code snippet. And one isn't sure after seeing it whether is applies to other such values and which ones. It would be nice if that were made clear in its own section on that page.

**Comment by meredithslota** [comment]
We've revamped the documentation on this (https://cloud.google.com/datastore/docs/concepts/queries#projection_queries) and there are updated code samples. If this is still causing confusion, please file a new issue!
